############################################################
# Site Settings
url: "http://pixelart.io"
absurl: "http://pixelart.io"
author: Codrin Pavel

title: BestCMS
description: > # this means to ignore newlines
  Write an awesome description for your new site here. You can edit this
  line in _config.yml.

facebook_like: http://pixelart.io # OPTIONAL. false | url to like
facebook_appid: 1902799049933562
facebook_admin: 100000026051093
facebook_share_description: "Take your daily pixel art inspiration at pixelart.io"
facebook_share_caption: "PIXELART.COM"

twitter_username: pixelartIO
share_hashtags: "pixelart, pixel, art, pixelart.io" # OPTIONAL . false | "tags, for, twitter, &, tumblr"

splash: image.jpg

ga_id: UA-75349601-1

############################################################
# Template Settings
logo_html: 'PIXEL<span>art</span>'
sidebar_featured_headline: 'Featured pixels'
sidebar_follow_headline: 'Follow PIXELART.IO'


############################################################
# Build Settings
imgfolder: /assets/img/
baseurl: "" 
markdown: kramdown
excerpt_separator: "{readmore}"
plugins: 
  - jekyll-paginate-v2
#  - jekyll-minifier
exclude:
  - Gemfile
  - Gemfile.lock
permalink: /:title
collections:
  amp:
    output: true
    permalink: /:collection/:title

sass:
  sourcemap: true
  style: expanded
  line_comments: true
  trace_selectors: false
  debug_info: false
#theme: infinitescroll

future: true

############################################################
# Site configuration for the Jekyll 3 Pagination Gem
# The values here represent the defaults if nothing is set
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  # Set to 'true' to enable pagination debugging. This can be enabled in the site config or only for individual pagination pages
  debug: false

  # The default document collection to paginate if nothing is specified ('posts' is default)
  collection: 'posts'

  # How many objects per paginated page, used to be `paginate` (default: 0, means all)
  per_page: 10

  # The permalink structure for the paginated pages (this can be any level deep)
  permalink: '/page/:num/' # Pages are index.html inside this folder (default)
  #permalink: '/page/:num.html' # Pages are simple html files 
  #permalink: '/page/:num' # Pages are html files, linked jekyll extensionless permalink style.

  # Optional the title format for the paginated pages (supports :title for original page title, :num for pagination page number, :max for total number of pages)
  title: ':title - page :num'

  # Limit how many pagenated pages to create (default: 0, means all)
  limit: 0
  
  # Optional, defines the field that the posts should be sorted on (omit to default to 'date')
  sort_field: 'date'

  # Optional, sorts the posts in reverse order (omit to default decending or sort_reverse: true)
  sort_reverse: true

  # Optional, the default category to use, omit or just leave this as 'posts' to get a backwards-compatible behavior (all posts)
  category: 'posts'

  # Optional, the default tag to use, omit to disable
  tag: ''

  # Optional, the default locale to use, omit to disable (depends on a field 'locale' to be specified in the posts, 
  # in reality this can be any value, suggested are the Microsoft locale-codes (e.g. en_US, en_GB) or simply the ISO-639 language code )
  locale: '' 

 # Optional,omit or set both before and after to zero to disable. 
 # Controls how the pagination trail for the paginated pages look like. 
  trail: 
    before: 2
    after: 2

############################################################