url: "http://pixelart.io"
absurl: "http://pixelart.io"
author: "Codrin Pavel"
title: PixelArt
logo_html: "PIXELART<span>.IO</span>"
description: "Daily pixel art inspiration for all your pixel needs."
facebook_like: "https://www.facebook.com/pixelartio"
facebook_appid: 1344412318946948
facebook_admin: 100000026051093
facebook_share_description: "Take your daily pixel art inspiration at pixelart.io"
facebook_share_caption: "PIXELART.COM"
twitter_username: pixelartIO
share_hashtags: pixelart
splash: ""
ga_id: "UA-75349601-1"
site_verification: YmVoqteYV2uUrrnR8rBjmbwP40Ytfza3ar95opJSUj4
sidebar_featured_headline: "Featured pixels"
sidebar_featured_creators_headline: "Featured Artists"
sidebar_follow_headline: "Follow PIXELART.IO"
imgfolder: "/assets/img/"
baseurl: ""
markdown: kramdown
excerpt_separator: "{readmore}"
plugins: 
  - "jekyll-paginate-v2"
exclude: 
  - Gemfile
  - "Gemfile.lock"
permalink: "/:title"
collections: 
  amp: 
    output: true
    permalink: "/:collection/:title"
sass: 
  sourcemap: true
  style: expanded
  line_comments: false
  trace_selectors: false
  debug_info: false
future: true
pagination: 
  enabled: true
  debug: false
  collection: posts
  per_page: 10
  permalink: "/page/:num/"
  title: ":title - page :num"
  limit: 0
  sort_field: date
  sort_reverse: true
  category: posts
  tag: ""
  locale: ""
  trail: 
    before: 2
    after: 2