is_production: true
baseurl: "/"
url: "https://pixelart.io"

name: pixelart.io # for og:site_name
title: For your Pixel Art inspiration needs # default meta title
description: Find incredible Pixel Art characters, animations, games, assets and more! # default meta description
image: false # social share image
theme_color: '#2962cd'

ga: "UA-75349601-1" # Google Analytics
google_site_verification: YmVoqteYV2uUrrnR8rBjmbwP40Ytfza3ar95opJSUj4 # optional, Google Search Console verification

twitter_site: pixelartio # optional, for twitter cards - Twitter site account, without the @
twitter_tags: pixelart # comma,separated,list

markdown: kramdown
permalink: /:title/
future: true

exclude: ["_assets",
          "node_modules", 
          "CNAME",
          "Gemfile",
          "Gemfile.lock",
          "README.md",
          "gulpfile.js", 
          "gulpfile.git.js", 
          "gulpfile.editor.js", 
          "gulpfile.paths.js",
          "package.json", 
          "package-lock.json"]

collections:
  sections:
    output: true
    permalink: /:title/
